# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='url',
            new_name='website',
        ),
    ]
